[GLOBAL]
pants_version = "2.11.0"
pythonpath = ["%(buildroot)s/pants-plugins"]

backend_packages = [
    "pants.backend.python",
    "python_plugins.setup_py",
    "pants.backend.python.lint.black",
    "pants.backend.python.typecheck.mypy",
    "pants.backend.python.lint.flake8",
    "pants.backend.python.lint.isort",
    "pants.backend.python.lint.docformatter",
]

[source]
root_patterns = ["/yasr"]

[python]
interpreter_constraints = [">=3.8"]

[anonymous-telemetry]
enabled = false
